# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'centerGroupBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_centerGroupBox(object):
    def setupUi(self, centerGroupBox):
        centerGroupBox.setObjectName("centerGroupBox")
        centerGroupBox.resize(640, 480)
        self.gridLayout_2 = QtWidgets.QGridLayout(centerGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        self.insertGrid = QtWidgets.QGridLayout()
        self.insertGrid.setObjectName("insertGrid")
        self.insertEdit1 = QtWidgets.QLineEdit(centerGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.insertEdit1.sizePolicy().hasHeightForWidth())
        self.insertEdit1.setSizePolicy(sizePolicy)
        self.insertEdit1.setObjectName("insertEdit1")
        self.insertGrid.addWidget(self.insertEdit1, 0, 0, 1, 1)
        self.insertButton = QtWidgets.QPushButton(centerGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.insertButton.sizePolicy().hasHeightForWidth())
        self.insertButton.setSizePolicy(sizePolicy)
        self.insertButton.setObjectName("insertButton")
        self.insertGrid.addWidget(self.insertButton, 0, 2, 1, 1)
        self.insertEdit_2 = QtWidgets.QLineEdit(centerGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.insertEdit_2.sizePolicy().hasHeightForWidth())
        self.insertEdit_2.setSizePolicy(sizePolicy)
        self.insertEdit_2.setObjectName("insertEdit_2")
        self.insertGrid.addWidget(self.insertEdit_2, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.insertGrid, 3, 0, 1, 1)
        self.tableGrid = QtWidgets.QGridLayout()
        self.tableGrid.setObjectName("tableGrid")
        self.lineEdit = QtWidgets.QLineEdit(centerGroupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.tableGrid.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(centerGroupBox)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.tableGrid.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(centerGroupBox)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.tableGrid.addWidget(self.lineEdit_3, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(centerGroupBox)
        self.pushButton.setObjectName("pushButton")
        self.tableGrid.addWidget(self.pushButton, 0, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(centerGroupBox)
        self.pushButton_2.setObjectName("pushButton_2")
        self.tableGrid.addWidget(self.pushButton_2, 0, 3, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(centerGroupBox)
        self.pushButton_3.setObjectName("pushButton_3")
        self.tableGrid.addWidget(self.pushButton_3, 1, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(centerGroupBox)
        self.pushButton_4.setObjectName("pushButton_4")
        self.tableGrid.addWidget(self.pushButton_4, 1, 3, 1, 1)
        self.gridLayout_2.addLayout(self.tableGrid, 0, 0, 1, 1)

        self.retranslateUi(centerGroupBox)
        QtCore.QMetaObject.connectSlotsByName(centerGroupBox)

    def retranslateUi(self, centerGroupBox):
        _translate = QtCore.QCoreApplication.translate
        centerGroupBox.setWindowTitle(_translate("centerGroupBox", "GroupBox"))
        self.insertButton.setText(_translate("centerGroupBox", "Insert"))
        self.pushButton.setText(_translate("centerGroupBox", "PushButton"))
        self.pushButton_2.setText(_translate("centerGroupBox", "PushButton"))
        self.pushButton_3.setText(_translate("centerGroupBox", "PushButton"))
        self.pushButton_4.setText(_translate("centerGroupBox", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    centerGroupBox = QtWidgets.QGroupBox()
    ui = Ui_centerGroupBox()
    ui.setupUi(centerGroupBox)
    centerGroupBox.show()
    sys.exit(app.exec_())
