# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'centerGroupBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QGroupBox, QPushButton, QVBoxLayout


class CenterGroupBox(QGroupBox):
    def __init__(self, parent):
        super().__init__(parent)
        self.setTitle("Test")

        layoutVert1 = QVBoxLayout()
        spineBtn = QPushButton("Spine")

        # add widgets to the layouts
        layoutVert1.addWidget(spineBtn)
        # assign the layout to the groupBox
        self.setLayout(layoutVert1)

        self.setLayout(layoutVert1)
