# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'centerGroupBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtWidgets
from PyQt5.QtWidgets import QGroupBox, QPushButton, QGridLayout, QLabel, QLineEdit


class CenterGroupBox(QGroupBox):
    def __init__(self, parent):
        super().__init__(parent)
        self.setTitle("Table")

        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName("gridLayout")

        # assign the layout to the groupBox
        # self.setLayout(self.gridLayout)

        layoutForSpacer = QGridLayout(self)
        layoutForSpacer.addLayout(self.gridLayout, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        layoutForSpacer.addItem(spacerItem, 1, 0, 1, 1)

    def buildTable(self, columns, rows, callback):
        self._deleteAll()

        for i, column in enumerate(columns):
            self.gridLayout.addWidget(QLabel(column), 0, i)

        for r_index, row in enumerate(rows):
            line = []
            for c_index, field in enumerate(row):
                edit = QLineEdit(str(field))
                edit.returnPressed.connect(lambda r=r_index: callback("update", r))
                line.append(edit)
                self.gridLayout.addWidget(edit, r_index + 1, c_index)
            update = QPushButton("Update")
            delete = QPushButton("Delete")
            update.clicked.connect(lambda _, r=r_index: callback("update", r))
            delete.clicked.connect(lambda _, r=r_index: callback("delete", r))
            self.gridLayout.addWidget(update, r_index + 1, c_index + 1)
            self.gridLayout.addWidget(delete, r_index + 1, c_index + 2)
            self.lineEdits.append(line)
            # self.updateButtons.append(update)
            # self.updateButtons.append(delete)

    def _deleteAll(self):
        for i in reversed(range(self.gridLayout.count())):
            self.gridLayout.itemAt(i).widget().deleteLater()
        self.lineEdits = []
        # self.updateButtons = []
        # self.deleteButtons = []
